Old Apple Website features
warblo001/AppleClone pull request #1
Opened 2020-10-02 11:17 UTC by warblo001

In this project we were tasked to create a clone from the Old Apple Website, using frontend technologies like gradients and backgrounds.
The project has the following features:
- Navigation Bar with gradients
- Backgrounds features on all the project
- Flexbox

2020-10-02 16:45 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Great job with this project, team! 👍 
Your navbar is impressive, an amazing job with it looks like the original 👏 
Good and descriptive commits and a good readme file 💯 
Good use of backgrounds and gradients 🥇 
Your code is clean 🔝  and well structured 👍 
Linters are green 🟢 

However, we must do some changes in order to get the project approved.
Check my comments below 👇  apply the changes and request for a new code review ⏩ 

Good luck with it 😃 

## Changes

- As I said, the navbar is amazing, but the positioning it is not correct, check the difference with the original and kindly modify it. You can use background-size and position properties.
Original:
![Capture](https://user-images.githubusercontent.com/56809963/94947192-83c5e480-04dd-11eb-8969-a812110ceb6e.PNG)

Your project:
![Capture1](https://user-images.githubusercontent.com/56809963/94947269-a657fd80-04dd-11eb-8372-105c4a260ee9.PNG)

- Good use of flex, but one of the mandatory requirements is that you have to use float as well.   
       Elements should be aligned with [float](https://css-tricks.com/all-about-floats/) and [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) or [grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/align_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538830/))

2020-10-02 16:45 UTC, javitocor commented on README.md
> +
[OPTIONAL]
You can add SASS here, remember to add all the techs you use in the readme to highlight it

2020-10-02 16:45 UTC, javitocor commented on README.md
> +
[OPTIONAL]

Add your LinkedIn link, recruiters will appreciate it

2020-10-05 09:56 UTC, arslanbisharat approved these changes
## Approved
Thank you for making those changes requested by previous TSE. 
This project is approved.
Regards,
Arslan Bisharat

2020-10-05 10:00 UTC, merged